
-- Question attributes
--[[
	Syntax summary
		AAA = 0
			Means that the value is intended to be a number
		AAA = ""
			Means that the value is intended to be a string
		AAA = true
		AAA = false
			Means that the value is intended to be a boolean
		AAA = {X}
			Means that the value is intended to be a table
			containing objects of type X
		AAA = BASE64
			Means that the value is intended to be converted
			into base64 format using the external converter
			addon, or using an online website. The base64 value
			should be encased by double quotes to make it a string.
		AAA = SHA2HASH
			Means that the value is intended to be a sha2 hash
			value that has been generated by the external converter
			addon (Not any other tool or website). The hash value
			should be encased by double quotes to make it a string.

REQ		AAA
			The prefix "REQ" next to an attribute means that it is
			required to be set for the question to be valid


	General attributes

REQ		ID = 0
			Unique identifier of the question, if two identical ID's
			are found then the addon will NOT work.
REQ		name = ""
			The name/title of the question
REQ		category = ""
			The category attribute can be set to either of four constants:
				ETW_EXPLORE_CATEGORY			Exploration category
				ETW_INVESTIGATION_CATEGORY		Investigation category
				ETW_TRACKING_CATEGORY			Tracking category
				ETW_GROUPQUEST_CATEGORY			Groupquest category
REQ 	continent = ""
			The continent attribute can be set to either of six constants:
				ETW_CONTINENT_KALIMDOR
				ETW_CONTINENT_EASTERN
				ETW_CONTINENT_OUTLAND
				ETW_CONTINENT_NORTHREND
				ETW_CONTINENT_PANDARIA
				ETW_CONTINENT_UNKNOWN
			They specify on which continent you answer the question to give
			a general idea where to look. If you can answer the question on
			multiple continents then the unknown constant is used as seen
			above.
REQ		description = ""
			Description of the question, which is the key part of it,
			explaining how it is accomplished in a not too obvious manner.
		author = ""
			Name of whoever made the question that will be displayed
			alongside the question as it is viewed. The default author
			value will be the addon author.

	Texture attributes (background texture for the image frame)

		texturepath = ""
			Path to a texture within the WoW directory, the best way to
			find these paths is to export the WoW art, google how to do so.
		texturewidth = 0
			Width of the texture, and also the image/model frame
		textureheight = 0
			Height of the texture, and also the image/model frame
		textureCropLeft = 0
			Value between 0 and 1 that defines where on the left side the texture
			should be cropped
		textureCropRight = 0
			Value between 0 and 1 that defines where on the right side the texture
			should be cropped
		textureCropTop = 0
			Value between 0 and 1 that defines where on the top side the texture
			should be cropped
		textureCropBottom = 0
			Value between 0 and 1 that defines where on the bottom side the texture
			should be cropped

	Model attributes

		modelId = BASE64
			Display id of the NPC model converted to base64 format. The
			displayId can be found by going to the wowhead page of the
			NPC you want the model of, view source of the page and search
			for "displayId". As Wowhead has 3D models of NPC's they also
			make use of displayId's. Used instead of modelPath.
		modelPath = BASE64
			Path to a model file within the WoW directory, converted to
			base64 format. Used instead of modelId.
		modelZoom = 0
			Zooming factor when displaying a non-NPC model, i.e a model
			specified with the "modelPath" attribute. Smaller values will 
			display a bigger model and bigger values a smaller model.
		modelYOffset = 0
			Simple Y offset (up/down) if the model is too far down or up.
		modelXOffset = 0
			Simple X offset (up/down) if the model is too far left or right.

	Unlock attributes
		With an ID of over ETW_DEFAULT_QUESTION_ID, either of these are "REQ", i.e required

		zoneUnlockHash = {SHA2HASH}
			Table of zones that unlock the questions when entered, subzones
			or map zones, any zone. The hash values should be of the ZONE NAME.
		itemUnlockHash = {SHA2HASH}
			Table of items that unlock the question when looted. The hash
			values should be of the ITEM ID. (http://www.wowhead.com/item=49623)
			Then 49623 is the ID.
		npcUnlockHash = {SHA2HASH}
			Table of npc's that unlocked the question when targeted. The hash
			values should be of the NPC NAME.
		worldObjectUnlockHash = {SHA2HASH}
			Table of world objects that unlocks the question when interacted with,
			for example a tombstone on the ground or a book in your inventory. The
			hash value should be of the WORLD OBJECT NAME.
		progressUnlockHash = SHA2HASH
			Amount of completed quests that unlocks the question. The hash value should
			be of the NUMBER OF COMPLETED QUESTS. For example 5 if you want the question
			to unlock after 5 completed quests.
		zoneRequirementUnlockHash = {SHA2HASH}
			Optional attribute, table of zones that you have to be at to unlock the
			question. So if you have a question unlock from an NPC, but the NPC can be
			found in various places, you might only want the question to unlock at a 
			certain place.
		zoneRequirementUnlockCopy = true
			If this attribute is true, then the value of "zoneRequirementUnlockHash" will
			be equal to that of "zoneRequirementHash"
		questionUnlock = {BASE64}
			Table of questions that will make the question unlock when answered. The table
			values should be the base64 format of the QUESTION ID of the question that
			unlocks the question.

	Answer attributes
				
REQ		answer = {SHA2HASH}
			A table of all the possible answers for a question, all
			in sha2 hash format.
REQ		zoneRequirementHash = 
		{
			{ zone = SHA2HASH, subZone = SHA2HASH }
		}
			A table of all the zones that you're allowed to answer the
			question in. The table contains a list of smaller tables,
			each of the smaller tables may contain a "zone" and a "subZone"
			value. The attribute "zone" here defines a zone that the player
			must be in, for example "Tanaris" or "Shadowfang Keep". The
			attribute "subZone" in this case then allows you to define a subzone
			that the player must be in. For example "The Dark Portal" in
			Blasted Lands or "The Canal" in Stormwind. Both "zone" and "subZone"
			are in sha2 hash format.

		OR IF IT IS A GROUPQUEST

REQ 	groupQuestCategory = ""
			See the "category" attribute
REQ 	groupQuest = 
		{
			[1] =
			{
				answer = {SHA2HASH},
				zoneRequirementHash = {{ zone = SHA2HASH, subZone = SHA2HASH }}
			}
			[2] = 
			{
				answer = {SHA2HASH},
				zoneRequirementHash = {{ zone = SHA2HASH, subZone = SHA2HASH }}
			}
		}
			Answer data for a groupquest, a table of 2-5 "mini-questions" that
			contain answer and zoneRequirementHash. Each of these mini questions
			must be answered by separate people in a group, at the same time. That
			is, for a groupquest the mini questions are the objectives of the 
			group question.

]]


ETW_LoreQuestions = {

	defaultQuestion = 
	{
		texturepath = "Interface\\Glues\\Models\\UI_Worgen\\UI_Worgen_BG05a.blp",
		texturewidth = 250,
		textureheight = 152,
		textureCropLeft = 0,
		textureCropRight = 1,
		textureCropTop = 0,
		textureCropBottom = 1
	},

	questions = 
	{
		
		{
			ID = 1,
			name = "The TV Chef",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "Mzc2NDU=",
			description = "A reference to a famous TV chef, most notably known for his hosting of various competitive cooking shows, often in quite the angry mood. Although here we have him relaxing at qutie the resort, with hot springs and steamy food just around the corner.",
			answer =
			{
				"f58b1a0e27867ef20567fd832481aed54e152c46a1c07ed4f9c3aeef8b27e790"
			},
			zoneRequirementHash = 
			{
				{ zone="d75d71989b25d8114bdeeedd4f36d9b5fb8ba548ae1a66cf52329cb691330a7b", subZone="8d0ff8c7feb9ef111a36d09695309f0cd808c38b420626ac2edd2b9531bac61d"}
			}
		},
		{
			ID = 2,
			name = "Sorrow by Quilboar",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "Mzg1NQ==",
			description = "Living a dry barren land this poor orc had his wife killed by the quilboar, but sought revenge on them through helpfull heroes of the Horde. Not too far from the watch post he resides, consumed by his hatred against the quilboar.",
			answer =
			{
				"3007b3f7b3762071034b5525693b2be41c01a210b5725669975dabc5be855e4f"
			},
			zoneRequirementHash = 
			{
				{ zone="8231b7f748e85a746e443e3e16371c434fe51068382472029cad77f64af40fd1"}
			}
		},
		{
			ID = 3,
			name = "\"Defenseless\" critters",
			category = ETW_INVESTIGATION_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "MzI4",
			description = "Green plains, plainstriders and kodos are just a few of the things you can find in this zone. Not to mention, critters such as rabbits and prairie dogs can be found using weapons here. Amongst these critters is a decorated stone, name one thing on the stone.",
			answer =
			{
				"e3bfe7e56a821737615132e603dbe6beaf6936710f634d4573250b784e58ae56",
				"994375f2f240a510dc3af273547d2a553afbea00b088a4f57871ab45c544becd",
				"edfce16ce1f01e070207fafeadbe6f498516e54cf97292d18c6b3823e893f175",
				"3e9e7a46c3b80b73483e3129771401ccdaed1d2eff632a824984d489a86a5dea"
			},
			zoneRequirementHash = 
			{
				{ zone="798f715b8bfe09111da2750514181ac9f9eaf1f7a5333ba41bfe907fbdea9df5"}
			}
		},
		{
			ID = 4,
			name = "Consumed by shadows",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "NTQzMA==",
			description = "Hidden in a secret cave, one of the lesser known Demon Hunters can be found. Should you fall into this void, fear not, for the Cenarion Circle will be able to help you away from the ghosts in the darkness.",
			answer =
			{
				"088b0b86b90297d53e81ffe6efe6a13519398e4afc7bd282907cc9e6828f859a"
			},
			zoneRequirementHash = 
			{
				{ zone="9d02d0c7eb122f18cbf34943e43fdc6a96ee00dbc9080c59026278ea4033de6e", subZone="088b0b86b90297d53e81ffe6efe6a13519398e4afc7bd282907cc9e6828f859a"}
			}
		},
		{
			ID = 5,
			name = "Steel wool producer",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "NDA1MQ==",
			description = "A gnome with a secret farm of wool producing animals located on a beautiful grasscovered hillside. One of these animals is \"modified\" to suit other needs which we do not know of other than to amuse rude adventurers passing by.",
			answer =
			{
				"8ccff692cd12807cf8ac17e31472f44ef0a00d586534150a865bfb7a2714d14a"
			},
			zoneRequirementHash = 
			{
				{ zone="736aaecfc1f584a92486b54aab7ba65d94e6870d5fc4413daa3abca296b4ef0b"}
			}
		},
		{
			ID = 6,
			name = "Kill for Booty",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelPath = "V29ybGRcXEF6ZXJvdGhcXHN0cmFuZ2xldGhvcm5cXHBhc3NpdmVkb29kYWRzXFxydWluc1xcc3RyYW5nbGV0aG9ybnJ1aW5zMDIubWR4",
			description = "It was built by the ancient jungle trolls but is now reclaimed by the surrounding vegetation. Although occasionally a short fellow bribes adventurers to once again fill the long forgotten battle ring, with blood.",
			answer =
			{
				"c2f3d971eafd12bef1e2226678e96ca8a3f5dcd372d61cd77c10c67780965cd4"
			},
			zoneRequirementHash = 
			{
				{ zone="2a373dec3bde04f90e30284c48c1e583082ea3a61dbe94be0dc9bc935fa20e44", subZone="c2f3d971eafd12bef1e2226678e96ca8a3f5dcd372d61cd77c10c67780965cd4"}
			}
		},
		{
			ID = 7,
			name = "The assassinator",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "NTUyOA==",
			description = "A grand master in the fine artmanship of assassinating designated targets, even a leader in a league teaching just that. Located in a training camp up in the mountains, east from the mill, and north from the south.",
			answer =
			{
				"11ee54b26794b998c485503886d3649b3a82b9c46578fb664704afb1c14f57d3"
			},
			zoneRequirementHash =
			{
				{ zone="50ffd9e239f0b31b94298b59f862e0b454919e64120c54905eb771f6877ced61", subZone="0dc11dfaf6c36a4bb6570560942a387182b38b898bf5a82155622fc89df0e464"}
			}
		},
		{
			ID = 8,
			name = "Hidden between lands",
			category = ETW_INVESTIGATION_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelPath = "V29ybGRcXEdlbmVyaWNcXGR3YXJmXFxwYXNzaXZlIGRvb2RhZHNcXGJhdHRsZW1lbnRzXFxkd2FydmVuYmF0dGxlbWVudG1vc3N5MDIubWR4",
			modelZoom = 7,
			description = "Just south of the overpass combining highlands with wetlands is a dwarven city that is overrun by the Twilight Cult. What may not be known to all is something hidden in the surrounding mountains, what is it?",
			answer =
			{
				"0219f20d577c297930f0b758f6a140f522174b3a142b9d278d8937c4c0125fbc",
				"e4755cb31c0fffb72499cb3f86cbbceda5ba47c5c7693aa58af164e54d64024b",
				"3379897f09bbf26bc35f553e9396f58e83a903573995dd110f262c3d136d84a8"
			},
			zoneRequirementHash =
			{
				{ zone="d05b2fc34d0e44c9fb14f601d1794ae1755e91f373d7c679e51ccba0cb34f56a"}
			}
		},
		{
			ID = 9,
			name = "Trogg liberty",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "NTk0NQ==",
			description = "Carved out of stone as a symbol for liberty, now held captive by trogg that has overrun the excavation site. Not even adventurers from the nearby lodge or loch has bothered to dig her up out of the dirt.",
			answer =
			{
				"1a7750fb59a30dbe4133444d07a45910edcce9bb4f7e5be2293c83c4d7434cab"
			},
			zoneRequirementHash =
			{
				{ zone="4edc4b26add532fa92ae3b8bf439bd13aa959daf30f15469a0cbfc3248176681", subZone="1a7750fb59a30dbe4133444d07a45910edcce9bb4f7e5be2293c83c4d7434cab"}
			}
		},
		{
			ID = 10,
			name = "Requirement: Be rich",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelPath = "V29ybGRcXEdlbmVyaWNcXGdvYmxpblxccGFzc2l2ZWRvb2RhZHNcXGJlZHNcXGdvYmxpbl9ob3JkZV9vcm5hdGViZWRfMDEubWR4",
			modelZoom = 2,
			description = "A luxurious retreat for the richest of business men, complete with endless hordes of servants and a pool making use of the finest engineering has to offer. Assuming you have highly positioned friends within the cartel, bring a few million gold to fully experience this palace.",
			answer =
			{
				"483c193d49c8a7fd30802ae41eb73746e3484de4cfda55d412165f02f60f2445"
			},
			zoneRequirementHash =
			{
				{ zone="e5fe4f3372ed35b4f76c83df897e4d0e9372f9d50b498f5893b468e3bfae89a8", subZone="483c193d49c8a7fd30802ae41eb73746e3484de4cfda55d412165f02f60f2445"}
			}
		},
		{
			ID = 11,
			name = "Trapped by bears",
			category = ETW_INVESTIGATION_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "NzA3",
			description = "By the western edge of the region that is home to the great forge we find a camp that appears to be overrun by wild animals. But where are the owners of this small camp, surely they must be nearby as the fire is still burning.",
			answer = 
			{
				"dbc75b42b12c2a1ddccb94ade789aa654c5577702ad40c043f65b70873d7e02e",
				"e1f5380ecdd7e582eb7ae4cf3e93498877974dd38bf4fa8b0f5a5fdc6177477a",
				"f8565e1aa585890db7a5be060456734036c909cd28ea4d448de7206c8e26b54c",
				"4edb4b1d896eae5c81ff50dfe4ca35c6f95cfbaa15d7824ae02151f160bc0047"
			},
			zoneRequirementHash =
			{
				{ zone="73b5f5b9f0766caa35b01c58a76c0ebe71d8939f7de881ea108b4b25742e8ce6"}
			}
		},
		{
			ID = 12,
			name = "House of Wolves",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelYOffset = 0.8,
			modelPath = "V29ybGRcXEV4cGFuc2lvbjAzXFxkb29kYWRzXFx3b3JnZW5cXGl0ZW1zXFx3b3JnZW5fc3RhZ2Vjb2FjaF8wMS5tZHg=",
			description = "Standing strong throughout the effects of the cataclysm as its surrounding areas begin to crumble down the cliffside into the water. At the top of the hill we find this manor owned by those who transform at fullmoon.",
			answer =
			{
				"157f113b8b3695becf1f1f4462c79f2adb8e095ab5151f1d022f027e93e89f24"
			},
			zoneRequirementHash =
			{
				{ zone="ea08da2bd30e28a83f573f469b595a816cec54a34e971252d2f6ca2d8e6fd0af", subZone="157f113b8b3695becf1f1f4462c79f2adb8e095ab5151f1d022f027e93e89f24"},
				{ zone="fdb767ca3ec0d0d14f9c6ab095559d20aff15776b8c6e36170612966c83fc0af", subZone="157f113b8b3695becf1f1f4462c79f2adb8e095ab5151f1d022f027e93e89f24"}
			}
		},
		{
			ID = 13,
			name = "The collector",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "MTE2NTM=",
			description = "As one of the few non-hostile Lost Ones he urges for more things to collect, often offering a small reward to adventures who bring something new. Found in a land blasted by magic, crawling with demons and other vile sorcery.",
			answer =
			{
				"78f420f27817ed2dd63e224282b301a6957efb9df4ae6aacafbc80dd43a1e771"
			},
			zoneRequirementHash =
			{
				{ zone="2a0fd71aa349b3c662105e52d182b2950325ca79f408064b351575b983dfebcb"}
			}
		},
		{
			ID = 14,
			name = "MK Memorial",
			category = ETW_INVESTIGATION_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "NTIzMw==",
			description = "In the hills south of a forgotten oasis lies the memorial of an illustrator who died during the development of World of Warcraft. His initials \"MK\" are carved into the shrine beneath his orc character, but what does the \"K\" stand for?",
			answer =
			{
				"7131851b0091461f260f3440c4b8fe71d9d81925a660878cad2bb7d9e50ab89d"
			},
			zoneRequirementHash =
			{
				{ zone="8231b7f748e85a746e443e3e16371c434fe51068382472029cad77f64af40fd1", subZone="5413291cee39af0aea00f533fa226ca3d7c0c6f428b5c5e4e5f56ef9293bd1c7"}
			}
		},
		{
			ID = 15,
			name = "Voices of the past",
			category = ETW_INVESTIGATION_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "MzEwMjE=",
			description = "Bells are ringing and people are cheering, all waiting for his return. That is until he reveals his new self to the king, his father. An historical event that can be relived as you enter the ruined city that is is now home to the Forsaken. What is it that happens during this event?",
			answer =
			{
				"a4747cd5b2f0d657aa56908bd42867f5c14ff352d041537fdea802ede7017273",
				"11afb9c11b0031ce00ba96700bf2a50c3628f99160e9b58c765030e499e4b3e2",
				"8b858ec5e5bc99b154f4c37d169a621de03e7ab2e5d4a6663281f1c8e7f37887",
				"25776fa0bf641799e025e40c29a31e95a7eae5b3677e01b0e6e4b6f8fc612272"
			},
			zoneRequirementHash =
			{
				{ zone="2cfa5f86f8caecee1e714c86b20f026d664ecae5714e01b586583766a1773eee", subZone="eefe6c1f89fa12da231d98e109f68d8ddbbdfa18bcab74be67c5f73868f95084"}
			}
		},
		{
			ID = 16,
			name = "In loving memory",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "MTU5OTM=",
			description = "He is found kneeling and saluting the memorial grave dedicated towards a close friend of one of the WoW developers, the person whos main character he was. Located to the east in the lands below the league of rogues, overlooking the sea.",
			answer =
			{
				"32eaa3ea7fcf0b4f7f38e7dbd2188cb6d33dadc3dd6fd3a259f765c382cc8913"
			},
			zoneRequirementHash =
			{
				{ zone="50ffd9e239f0b31b94298b59f862e0b454919e64120c54905eb771f6877ced61", subZone="30e1a2c068c564db211c09702df721c1b32357cf56fae5faf2c5da35bbcfeadd"},
				{ zone="50ffd9e239f0b31b94298b59f862e0b454919e64120c54905eb771f6877ced61", subZone="6cd3171458882a02f08666a741d33c2d0aa4ce4213494f1daf001288552800f8"}
			}
		},
		{
			ID = 17,
			name = "Chickens on the run",
			category = ETW_GROUPQUEST_CATEGORY,
			continent = ETW_CONTINENT_UNKNOWN,
			modelId = "NzkyMA==",
			modelYOffset = 0.1,
			description = "Mechanical critters spread across Azeroth after being lost by their goblin owner in Booty Bay. Found surrounded by yetis in a jungle not too far from Dire Maul, crashed on a lake island in the land of gryphons or in the mountains south of the cave that moves time itself.",
			groupQuestCategory = ETW_TRACKING_CATEGORY,
			groupQuest = 
			{
				[1] =
				{
					answer =
					{
						"8bee34cab7ae493f2848ff7fb527b0d038152f8e382f924e3a11b70835e1883f"
					},
					zoneRequirementHash =
					{
						{ zone="4405b6709391f7bc2833d5f4d1432c6e13a0613f98bf794280833afa1f7e3c53"}
					}
				},
				[2] =
				{
					answer = 
					{
						"eafcacdb00a30f261075633efd368a23c530de2de46672c379142f583939bb5e"
					},
					zoneRequirementHash =
					{
						{ zone="e9288d744b1ba953b6ac213c87456c57aeda811cd2fca0044c2f432484328cda"}
					}
				},
				[3] =
				{
					answer =
					{
						"45248be447123432752c81cd0995afab05fc0e5d80d2d622187144f6fa3cfd67"
					},
					zoneRequirementHash =
					{
						{ zone="d75d71989b25d8114bdeeedd4f36d9b5fb8ba548ae1a66cf52329cb691330a7b"}
					}
				}
			}

		},
		{
			ID = 18,
			name = "Opening the gates",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelPath = "V29ybGRcXEthbGltZG9yXFxzaWxpdGh1c1xccGFzc2l2ZWRvb2RhZHNcZ29uZ1xzaWxpdGhpZGdvbmcubWR4",
			modelYOffset = 1.4,
			description = "The place where the infamous gong is located, that once struck, completes the quest of opening the gates and forever after made you a legend. Rewarding you with a mount and title that will never again be obtainable. And amongst the insects that dwell nearby, you shall be forever known as lord.",
			answer =
			{
				"6b560f8b1b328bdbda98117216f7a86ce503c1b8759ac3b38cbfdd2e81daf1bd"
			},
			zoneRequirementHash =
			{
				{ zone="32d172b5e7fbdc37857a7d1425b10e339c0b338aee2478ae27016e8a37c7e99c", subZone="6b560f8b1b328bdbda98117216f7a86ce503c1b8759ac3b38cbfdd2e81daf1bd"}
			}
		},
		{
			ID = 19,
			name = "Island of employees",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelPath = "V29ybGRcXEdlbmVyaWNcXGh1bWFuXFxwYXNzaXZlIGRvb2RhZHNcXHN0b3Jtd2luZFxcc3Rvcm13aW5kX2dyYXZlc3RvbmVfMDkubWR4",
			modelZoom = 0.5,
			modelYOffset = 0.3,
			description = "A lake that in which an island full of Blizzard employee related NPC's can be found. That as of now, are serving an unknown purpose other than to attract curious adventures. Located directly north of the jungle ruins that are now home to satyrs, ogres and the undead.",
			answer =
			{
				"d8c68eadae8af5891426707a098333ef7b325460e0979248ae36514e6aaf8c1f"
			},
			zoneRequirementHash =
			{
				{ zone="d75d71989b25d8114bdeeedd4f36d9b5fb8ba548ae1a66cf52329cb691330a7b", subZone="d8c68eadae8af5891426707a098333ef7b325460e0979248ae36514e6aaf8c1f"}
			}
		},
		{
			ID = 20,
			name = "Retired admiral",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "MjM1MDk=",
			description = "After retiring he can be found endlessly fishing by his secluded house on the mountainside, guarded by his Booty Bay bodyguards. With Vashj'ir on the horizon and both Ironforge and Stormwind on an equal distance away, he sure picked a good location to retire at.",
			answer =
			{
				"f1d02f3e2311e902cd02c429154404d69cf243a3a40209adcacb95d935e82d4c"
			},
			zoneRequirementHash =
			{
				{ zone="73b5f5b9f0766caa35b01c58a76c0ebe71d8939f7de881ea108b4b25742e8ce6"}
			}
		},
		{
			ID = 21,
			name = "Robo-chicken mystery",
			category = ETW_INVESTIGATION_CATEGORY,
			continent = ETW_CONTINENT_UNKNOWN,
			modelId = "NzkyMA==",
			modelYOffset = 0.1,
			description = "There are three robot chickens that can be found in Azeroth, all wanted back by their owner in Booty Bay. What you might not know about these chickens is that they each have 2 unique letters at the end of their name, what do they mean?",
			answer =
			{
				"4869f908f491b6f5c9c6eb3f0eab004f54137fc7e36fe9800de5f14486fed4e9",
				"4405b6709391f7bc2833d5f4d1432c6e13a0613f98bf794280833afa1f7e3c53",
				"d75d71989b25d8114bdeeedd4f36d9b5fb8ba548ae1a66cf52329cb691330a7b",
				"539df6fa9856df0ed841122d035951e55517580932eb38cf934a1716570d8436",
				"331358067956b956143d4a8b207df3121f0f97dcd0ed8aa26d2e3bdbd2b8716b"
			},
			zoneRequirementHash =
			{
				{ zone="e9288d744b1ba953b6ac213c87456c57aeda811cd2fca0044c2f432484328cda"},
				{ zone="d75d71989b25d8114bdeeedd4f36d9b5fb8ba548ae1a66cf52329cb691330a7b"},
				{ zone="4405b6709391f7bc2833d5f4d1432c6e13a0613f98bf794280833afa1f7e3c53"}
			},
			zoneRequirementUnlockCopy = true,
			npcUnlockHash =
			{
				"eafcacdb00a30f261075633efd368a23c530de2de46672c379142f583939bb5e",
				"8bee34cab7ae493f2848ff7fb527b0d038152f8e382f924e3a11b70835e1883f",
				"45248be447123432752c81cd0995afab05fc0e5d80d2d622187144f6fa3cfd67"
			}
		},
		{
			ID = 22,
			name = "The baron's treasury",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelPath = "V29ybGRcXFNraWxsYWN0aXZhdGVkXFxjb250YWluZXJzXFx0cmVhc3VyZWNoZXN0MDIubWR4",
			modelZoom = 0.8,
			modelYOffset = 1,
			description = "A mighty goblin pirate of the bay, one of the few goblins with a unique voice. Hidden nearby, is his treasure, guarded by the cleaver. In plain sight for everyone to see, yet disguised. After being revealed by the Cataclysm, it is yet to be plundered.",
			answer =
			{
				"5966493e1651a97e514afe1b1fd0982d08f1216d9feb6ec51c1c4b71d8163a0a"
			},
			zoneRequirementHash =
			{
				{ zone="2a373dec3bde04f90e30284c48c1e583082ea3a61dbe94be0dc9bc935fa20e44", subZone="5966493e1651a97e514afe1b1fd0982d08f1216d9feb6ec51c1c4b71d8163a0a"}
			},
			npcUnlockHash =
			{
				"436813600fe0b3cfea9075a971d514467a2ad3a5bb9db416a453dcea70c6bef3"
			}
		},
		{
			ID = 23,
			name = "Doomguard ritual",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "MTQ1MzE",
			description = "In a forgotten time he taught skilled Warlocks the fine art of controlling a Doomguard. Nowadays he is but an artifact of the past, fulfilling no use other than to attract curious adventures in the tainted forest nearby.",
			answer =
			{
				"e3303f5d616f296a1783d75ba72ae10d96efd7c25771e0fec047388e75d229e8"
			},
			zoneRequirementHash =
			{
				{ zone="2a0fd71aa349b3c662105e52d182b2950325ca79f408064b351575b983dfebcb", subZone="f2a666c5477626329e900adbe9bc465598d685202e34d727c9d28733face6b78"}
			},
			zoneUnlockHash =
			{
				"2a0fd71aa349b3c662105e52d182b2950325ca79f408064b351575b983dfebcb"
			}
		},
		{
			ID = 24,
			name = "Mountain mechanic",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "MTA0NTQ=",
			description = "Unlike most of his engineer colleagues, this trainer isn't located at a capital city. As a goblin he has decided to remain close to the nearby Venture Co mining operation. Overlooking green plains and some distant bluffs from the mountainside.",
			answer =
			{
				"9ab5e9292b86012d4c9b5e4508d972915b9df7e3ca11872d5618a53e9edd3383"
			},
			zoneRequirementHash =
			{
				{ zone="798f715b8bfe09111da2750514181ac9f9eaf1f7a5333ba41bfe907fbdea9df5"}
			},
			zoneUnlockHash =
			{
				"13e084c1def9e80292a1b052a9d98bd7c8fe281fad9b6b90ac4114ee44334847"
			}
		},
		{
			ID = 25,
			name = "Gnome of evil",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "MTU1NTc=",
			description = "One of the toughest gnomes in all of Kalimdor, showing himself worthy as a part of the Ahn'Qiraj quest chain. With HP close to that of MoP creatures he resides in his house, guarded by nagas, dragons and even hydras. On a tropical island that is better left unvisited.",
			answer =
			{
				"6a3be8b4457d4a4fef197c9fd5613c1c9ca56b149d3f5c524c1b31284a4f0b87"
			},
			zoneRequirementHash =
			{
				{ zone="8e8d0136b6b7b15a38f3564489032acc8e81198bf2f4b27ae154bca96b0c909f", subZone="276748e1be000dedad252f4e6c3f62743c564257413f8d1bd076bd6a2f7b054c"}
			},
			zoneUnlockHash =
			{
				"32d172b5e7fbdc37857a7d1425b10e339c0b338aee2478ae27016e8a37c7e99c"
			}
		},
		{
			ID = 26,
			name = "Band manager",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_UNKNOWN,
			modelId = "MjE5NTk=",
			description = "Manager of the most well-known band in all of Azeroth and Outland. Often found relaxing backstage with his black sunglasses on. Whether it be behind the stage at the faire, or below the band's balcony lounge in the capital where they are out of physical reach for fans.",
			answer =
			{
				"a484aa23b0918f9602cf50adb637e6c08ff6c517605507a6abf7fcaa213ab5a1"
			},
			zoneRequirementHash =
			{
				{ zone="c1d87ff59f026782923d2b0fdffa6feb989573946299cf1684399c8b68852665"},
				{ zone="35bb898a5832f324fc595ad6c6200a126ffe49b60119be38170da1e6f1245aaa"}
			},
			progressUnlockHash = "54bd0eb8cfde399f0436509703411a3ec29744b6b98b54b148bdc6c485a2d5fc"
		},
		{
			ID = 27,
			name = "Interrupted fishing",
			category = ETW_INVESTIGATION_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelPath = "V29ybGRcXEdlbmVyaWNcXGRvb2RhZHNcXGZpc2hpbmdcXGNoYWlyXFxmaXNoaW5nY2hhaXIubWR4",
			modelZoom = 1.5,
			modelYOffset = 1.2,
			modelXOffset = -0.65,
			description = "Someone was having a pretty relaxed fishing trip on a small island in shallow waters. Located by the opposite border from where King Arthas buried his beloved steed. But the fisher isn't fishing there anymore, what happened?",
			answer =
			{
				"c273f12aa9219ecc77fdd9efe1996251197d823dbe3b3fb22f18a9059629ff25",
				"4e27a7cd247296a1aff531b6c064baaca096e780a34cc2a2031b65b2d0a85fb7",
				"c8ef66e59a3d324fcb2f104297900deb3c7cdaa72ef9a639ad7d2402a0cbd473",
				"99722e4e2f757f8769503f3ddebf8986653401c607af1b12e8066f2b6a9184c7",
				"a519bbb06f9f05c5bdd9d740a47c48c0db88cb1fb67276b511eedf796872e729",
				"eecf72212b240c3d6b82b14a812f1c359d41a45f7b2cd44ac095a910a39afae9"
			},
			zoneRequirementHash =
			{
				{ zone="99f577e78adf6e383ab1e310ce4f0b8eb1c27ab4f3b02b1980ea78ccbde2654e"}
			},
			zoneUnlockHash =
			{
				"99f577e78adf6e383ab1e310ce4f0b8eb1c27ab4f3b02b1980ea78ccbde2654e"
			}
		},
		{
			ID = 28,
			name = "The origin of a city",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelPath = "V29ybGRcXEV4cGFuc2lvbjAyXFxkb29kYWRzXFxkYWxhcmFuXFxkYWxhcmFuX2NyYXRlcmRvbWUubWR4",
			modelZoom = 13,
			description = "The floating city of Dalaran has not always been located in Northrend, nor in the air. It has now left a crater from where it was originally located, west of the league of rogues and south of the kingdom where Arthas used to be prince.",
			answer =
			{
				"ef293107a37d997d25d9f80696135f5dd52c4eda3012ebab86f3c61ef1d297f2"
			},
			zoneRequirementHash =
			{
				{ zone="50ffd9e239f0b31b94298b59f862e0b454919e64120c54905eb771f6877ced61"}
			},
			zoneUnlockHash =
			{
				"1258cc3e7925d569f088d55c16ce09593c0312971d49730854910ac4c1c4cb98"
			}
		},
		{
			ID = 29,
			name = "Botanist defence",
			category = ETW_INVESTIGATION_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "MzY1NzU=",
			description = "In the lands west of Alterac Valley a curious farmer seems to have a constant problem with creatures attacking his property. Adventurers usually help him in the defence using what the farmer has available, which is what?",
			answer =
			{
				"1e7f394302d99ad73164dc2536a9f8d26526b9618c8b3fce6aaf8993d400c8fe",
				"401d8c17c79a30ce621838b6df8bf93803a26761423daf4423ff616a7c6b1214"
			},
			zoneRequirementHash =
			{
				{ zone="50ffd9e239f0b31b94298b59f862e0b454919e64120c54905eb771f6877ced61", subZone="0b1a7ec8ff9cbaf1d3f3a0c673fbaa07189aef5fdc979e9190791630d7595aea"}
			},
			zoneUnlockHash =
			{
				"50ffd9e239f0b31b94298b59f862e0b454919e64120c54905eb771f6877ced61"
			}
		},
		{
			ID = 30,
			name = "An archaeologist's pet",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "MTUzMDI=",
			description = "It would appear that all the exploring and Titan database hacking has made him forgot about his friends. His long forgotten companion still waits patiently for his return at the dwarven encampment, overlooking the crystal filled sand flats.",
			answer =
			{
				"2fab0a100a5958fb8db10b876bbf53064e778e96d8f3282a719071e798c2a353"
			},
			zoneRequirementHash =
			{
				{ zone="32d172b5e7fbdc37857a7d1425b10e339c0b338aee2478ae27016e8a37c7e99c", subZone="c5824e2015596f79ba76096791b0313a2fc5657f15cad58212a8f6f1fe32f8c3"}
			},
			itemUnlockHash =
			{
				"de8d83d5ae8a2cf75569a8a5680c1fd04b12e07d22b0ed9d87e6ba73931dd32a"
			},
			npcUnlockHash =
			{
				"ffbb7f740e6deece0cc8cc194c3442d8d12491691b3b9be7bd0963012c7a9c65"
			}
		},
		{
			ID = 31,
			name = "Along for the ride",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "MzExNzQ=",
			description = "Getting pulled around, eagerly awaiting to have a ride down the mountain. But he'll have to satisfy with watching the others have fun. Afterall, if he misses the pile at the bottom of the hill then the large hangar behind isn't going to give a comfortable stop to the ride.",
			answer =
			{
				"f6b5367205f3974f0d69315587c43d8bfbfb02d6cbcdeb78e285e3d0c850f977"
			},
			zoneRequirementHash =
			{
				{ zone="73b5f5b9f0766caa35b01c58a76c0ebe71d8939f7de881ea108b4b25742e8ce6"}
			},
			progressUnlockHash = "54bd0eb8cfde399f0436509703411a3ec29744b6b98b54b148bdc6c485a2d5fc"
		},
		{
			ID = 32,
			name = "Making a wish",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_PANDARIA,
			modelPath = "V29ybGRcXEV4cGFuc2lvbjA0XFxkb29kYWRzXFxwYW5kYXJlblxcbGFudGVyblxccGFfbGFudGVybl9mbG9hdGluZ18wMV9kZXN0cm95ZWQubWR4",
			modelZoom = 0.5,
			modelYOffset = 0.4,
			description = "In the beautiful green forest, with vessels of both factions lurking in the waters below, a wishing well can be found. Made as a tribute to a young boy named Brian who suffered of bone cancer, whose last wish was to visit the Blizzard HQ and whose nickname names the wishing well.",
			answer =
			{
				"9be14520ef83faa278020ea3816d9e901374e79c2128d79a6bd71423b8903726"
			},
			zoneRequirementHash =
			{
				{ zone="fad3ca4dd79ea23d6f0bc3d698ce2a935678bc82d1a9a3016de2d4348bfa7b5c", subZone="9be14520ef83faa278020ea3816d9e901374e79c2128d79a6bd71423b8903726"}
			},
			questionUnlock = 
			{
				"MTQ="
			}
		},
		{
			ID = 33,
			name = "Friend or foe?",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_NORTHREND,
			modelId = "MjU5OTg=",
			description = "These 2 'brothers' met in Quel'thalas, where eventually one of them killed the other. They were both raised as a death knight by Arthas. After beeing freed from the Scourge by Tirion Fordring, they seperated into the Alliance and Horde. Find either of these 2 friends on their factions ship.",
			answer =
			{
				"42ce1c85ac08192d877509bacb0db38b83106e5c13769a5c7d6ffedf0b0d95b7",
				"fe3834bddc109276775e95196137d273a3f14c268aa8cde97dfd42d917c017e0",
			},
			zoneRequirementHash =
			{
				{zone="785f4154f54111e999354e89d2fb6dea40272887bbf98e25d114704a57b55ec6"}
			},
			zoneUnlockHash = 
			{
				"ba4a4cbf46c8a4a9b65f180f277a9d6ba590686e371349191b774bf0d2c72273"
			},
			author = "Argathom",
		},
		{
			ID = 34,
			name = "Beings of Light",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_OUTLAND,
			modelId = "MTcwNzI=",
			description = "A'dal is one of the Naaru, a pure being of light. Yet there are more Naaru. Find the next Naaru in a vessel with which the Draenei arrived on Draenor, that became sacred to the orcs later on.",
			answer =
			{
				"f3dac27c33f3ff57cd5f4d83dbffe733c7f6a1657d0d5c2057c0296726f662ef",
			},
			zoneRequirementHash =
			{
				{zone="3e9158840b73b38c814569d333cf5b03b9a6c1ec6591fd08e3586355fc2f3c1d", subZone="3e602eee61c2b1f51f93951b90ca345b7b79ced2c0df14e280e4c6920bf483fe"}
			},
			npcUnlockHash =
			{
				"9464f02b65605ca8b230691ab235b86b7366bd85e2853c3fd43d9359a1b24d89"
			},
			author = "Argathom",
		},
		{
			ID = 35,
			name = "Beings of Light part 2",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_OUTLAND,
			modelId = "MTgxMzU=",
			description = "The Draenei used Oshu'gun as a ship to flee from the Burning Legion on Eredar. There were more then one Naaru on this vessel. The next Naaru 'died' when the ship crash landed on Draenor. He is buried in the crypt of a mausoleum.",
			answer =
			{
				"cf8c6fc78bb32aeabfaf60a850b191d99fd43ced7c1fdedc7cddd712c4e5cc01",
			},
			zoneRequirementHash =
			{
				{zone="2ae4ce21b40611b0b2cc6187089f26b1758439a2519ae89172c0171fafbaf00c"}
			},
			questionUnlock =
			{
				"MzQ="
			},
			author = "Argathom",
		},
		{
			ID = 36,
			name = "Beings of Light part 3",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "MjM0MDQ=",
			description = "The Naaru don't die, but enter a darkened state as you can see with the Naaru you just found. In this state they suck up the souls of the dead to recover their light. The next Naaru has been completely drained of the light by a knightly lady sworn to blood, and the naaru in question is now killable.",
			answer =
			{
				"e44a5a3bf472d865c130b8a1040bbba5c6d67fd33ffb27805b0ade5a852fe373",
			},
			zoneRequirementHash =
			{
				{zone="fe2d464d7114f5a0fc99f36c2e55846425a0abc1eb2a89f46fe54cbaad0debad"}
			},
			questionUnlock =
			{
				"MzU="
			},
			author = "Argathom",
		},
		{
			ID = 37,
			name = "Beings of Light part 4",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_KALIMDOR,
			modelId = "MTgxNTQ=",
			description = "Prophet Velen got help from the Naaru to continuously escape from the Burning Legion. Find the Naaru that helped the Draenei on their latest escape to a new world.",
			answer =
			{
				"3950e035e2d982a39c4176c60fa3010498f81ed8b3215f7eba2e0b047b9fe6c9",
			},
			zoneRequirementHash =
			{
				{zone="2456fe11bec8acade65f58288b83c3d041e47b5acc41c6875fda88ec2f2088aa"}
			},
			questionUnlock =
			{
				"MzY="
			},
			author = "Argathom",
		},
		{
			ID = 38,
			name = "A ghostly battle",
			category = ETW_EXPLORE_CATEGORY,
			continent = ETW_CONTINENT_EASTERN,
			modelId = "MTA0NDU=",
			description = "This small town is abandoned after the scourge invasion, but after gathering the right artifacts from the past, you can relive the battle that took place in this small town.",
			answer =
			{
				"1d90e6a1174a00c25c30d3c2a79c63c12cda3b05fbf7d5040b01586a9adb7020",
			},
			zoneRequirementHash =
			{
				{zone = "eda5f8c9406e9accca1ccb2e4ee2f8acf767461fd419e2d704bdb25260034a92", subZone = "1d90e6a1174a00c25c30d3c2a79c63c12cda3b05fbf7d5040b01586a9adb7020"}
			},
			npcUnlockHash = 
			{
				"32fb4210d119ed30dc93a8cc941d4ce8df1be5cb650231f45477b048bca6037c",
				"2efc8386d1846594003943241a5d896cd7cdaee63c57a67738610109281ec968",
				"63b48f9e68954d239f7b04e91225cca4ad80e07848c6637371965bf372796f22",
				"b866ca133fcc58f55dd1e01bb6161f0fb0d26176dded9fc1fd8b1570b940c1c0",
				"30db0b8948e0eaede4813516554f0d6268131de21a898fa59fed5dd885e062a2",
				"c14bb430a180169b53a50a8822e2f9fdb665eb3f24b28b58885db90a1a063d6f",
				"e103c89793eb69d0ff8d57349fc60f76e12d01b760446397b698cf0c0c0df093",
			},
			author = "Argathom"
		},
		{
			ID = 39,
			name = "Socialite?",
			category = ETW_TRACKING_CATEGORY,
			continent = ETW_CONTINENT_OUTLAND,
			modelId = "MTgxNDg=",
			description = "This woman is most famous for having the biggest bags in Outland, and they are not cheap! Many others claim she's more then that, but those are just rumors.",
			answer =
			{
				"c303b5beceba88c3096e4984c4474a1afe3127e0201785deb1df71e8e0178232",
			},
			zoneRequirementHash = 
			{
				{zone = "0062ef4a0dfa758fae0ae92b123759d9d0301987d65108ce286df6bc5f012322"}
			},
			progressUnlockHash = "54bd0eb8cfde399f0436509703411a3ec29744b6b98b54b148bdc6c485a2d5fc",
			author = "Argathom"
		}

	}

}

-- Contains unlocking data for each question in tables
ETW_UnlockTable = {}

ETW_UnlockTable.zones = {}
ETW_UnlockTable.items = {}
ETW_UnlockTable.npcs = {}
ETW_UnlockTable.worldObjects = {}
ETW_UnlockTable.progress = {}
ETW_UnlockTable.questions = {}